// ═══════════════════════════════════════════
// EXPORT — EPUB, DOCX, Deployable ZIP
// "An EPUB is just a website in a trenchcoat"
// "A DOCX is XML that wished it was HTML"
// ═══════════════════════════════════════════

function getExportNovel() {
  const novel = STATE.novels[STATE.currentNovel];
  if (!novel || !novel.chapters.length) {
    alert('No novel selected or no chapters generated. Select a novel in the Library first.');
    return null;
  }
  return novel;
}

function sanitizeFilename(title) {
  return (title || 'novel').replace(/[^a-zA-Z0-9_-]/g, '_').slice(0, 40);
}

function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  setTimeout(() => { URL.revokeObjectURL(url); a.remove(); }, 100);
}

// ═══════════════════════════════════════════
// EPUB — XHTML files in a zip
// ═══════════════════════════════════════════
async function exportEpub() {
  const novel = getExportNovel();
  if (!novel) return;

  const title = extractTitle(novel.bible) || 'Untitled Novel';
  const uuid = 'urn:uuid:' + crypto.randomUUID();
  const zip = new JSZip();

  // mimetype must be first, uncompressed
  zip.file('mimetype', 'application/epub+zip', { compression: 'STORE' });

  // META-INF/container.xml
  zip.file('META-INF/container.xml', `<?xml version="1.0" encoding="UTF-8"?>
<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
  <rootfiles>
    <rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/>
  </rootfiles>
</container>`);

  // Chapter XHTML files
  const chapterFiles = novel.chapters.map((ch, i) => {
    const chTitle = ch.text.split('\n')[0].replace(/^Chapter\s+\d+:\s*/i, '').trim() || `Chapter ${i + 1}`;
    const paragraphs = ch.text.split('\n').filter(l => l.trim()).map(p =>
      `<p>${escXml(p)}</p>`
    ).join('\n');

    const xhtml = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head><title>${escXml(chTitle)}</title>
<style>body{font-family:Georgia,serif;line-height:1.7;margin:2em;color:#333}h1{font-size:1.4em;margin-bottom:1em}p{margin-bottom:0.8em}</style>
</head>
<body>
<h1>${escXml(chTitle)}</h1>
${paragraphs}
</body>
</html>`;
    const filename = `chapter${String(i + 1).padStart(2, '0')}.xhtml`;
    zip.file('OEBPS/' + filename, xhtml);
    return { filename, title: chTitle, id: `ch${i + 1}` };
  });

  // Title page
  zip.file('OEBPS/title.xhtml', `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head><title>${escXml(title)}</title>
<style>body{font-family:Georgia,serif;text-align:center;margin:4em 2em;color:#333}h1{font-size:2em;margin-bottom:0.5em}p{color:#666;font-style:italic}</style>
</head>
<body>
<h1>${escXml(title)}</h1>
<p>Generated by NaNoGEon</p>
</body>
</html>`);

  // Table of contents (NCX)
  const navPoints = chapterFiles.map((f, i) => `
    <navPoint id="${f.id}" playOrder="${i + 2}">
      <navLabel><text>${escXml(f.title)}</text></navLabel>
      <content src="${f.filename}"/>
    </navPoint>`).join('');

  zip.file('OEBPS/toc.ncx', `<?xml version="1.0" encoding="UTF-8"?>
<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1">
  <head><meta name="dtb:uid" content="${uuid}"/></head>
  <docTitle><text>${escXml(title)}</text></docTitle>
  <navMap>
    <navPoint id="title" playOrder="1">
      <navLabel><text>Title Page</text></navLabel>
      <content src="title.xhtml"/>
    </navPoint>${navPoints}
  </navMap>
</ncx>`);

  // Cover image (if available)
  let coverManifest = '';
  let coverMeta = '';
  if (novel.cover) {
    const b64 = novel.cover.replace(/^data:image\/\w+;base64,/, '');
    const imgType = novel.cover.match(/^data:image\/(\w+)/)?.[1] || 'png';
    zip.file(`OEBPS/cover.${imgType}`, b64, { base64: true });
    coverManifest = `<item id="cover-image" href="cover.${imgType}" media-type="image/${imgType}" properties="cover-image"/>`;
    coverMeta = `<meta name="cover" content="cover-image"/>`;
  }

  // content.opf (package file)
  const manifestItems = chapterFiles.map(f =>
    `<item id="${f.id}" href="${f.filename}" media-type="application/xhtml+xml"/>`
  ).join('\n    ');
  const spineItems = chapterFiles.map(f =>
    `<itemref idref="${f.id}"/>`
  ).join('\n    ');

  zip.file('OEBPS/content.opf', `<?xml version="1.0" encoding="UTF-8"?>
<package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="uid">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
    <dc:identifier id="uid">${uuid}</dc:identifier>
    <dc:title>${escXml(title)}</dc:title>
    <dc:language>en</dc:language>
    <dc:creator>NaNoGEon</dc:creator>
    <meta property="dcterms:modified">${new Date().toISOString().split('.')[0]}Z</meta>
    ${coverMeta}
  </metadata>
  <manifest>
    <item id="title" href="title.xhtml" media-type="application/xhtml+xml"/>
    <item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml"/>
    ${coverManifest}
    ${manifestItems}
  </manifest>
  <spine toc="ncx">
    <itemref idref="title"/>
    ${spineItems}
  </spine>
</package>`);

  const blob = await zip.generateAsync({ type: 'blob', mimeType: 'application/epub+zip' });
  downloadBlob(blob, sanitizeFilename(title) + '.epub');
  awardSkull(4);
}

// ═══════════════════════════════════════════
// DOCX — XML in a zip
// ═══════════════════════════════════════════
async function exportDocx() {
  const novel = getExportNovel();
  if (!novel) return;

  const title = extractTitle(novel.bible) || 'Untitled Novel';
  const zip = new JSZip();

  // [Content_Types].xml
  zip.file('[Content_Types].xml', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
</Types>`);

  // _rels/.rels
  zip.file('_rels/.rels', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>`);

  // word/_rels/document.xml.rels
  zip.file('word/_rels/document.xml.rels', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
</Relationships>`);

  // Build document body
  const w = 'http://schemas.openxmlformats.org/wordprocessingml/2006/main';
  let body = '';

  // Title
  body += `<w:p><w:pPr><w:pStyle w:val="Title"/><w:jc w:val="center"/></w:pPr>
    <w:r><w:rPr><w:b/><w:sz w:val="56"/></w:rPr><w:t>${escXml(title)}</w:t></w:r></w:p>`;
  body += `<w:p><w:pPr><w:jc w:val="center"/></w:pPr>
    <w:r><w:rPr><w:i/><w:color w:val="888888"/></w:rPr><w:t>Generated by NaNoGEon</w:t></w:r></w:p>`;
  body += `<w:p><w:r><w:br w:type="page"/></w:r></w:p>`;

  // Chapters
  novel.chapters.forEach((ch) => {
    const lines = ch.text.split('\n').filter(l => l.trim());
    lines.forEach((line, j) => {
      if (j === 0 && line.match(/^Chapter\s+\d+/i)) {
        // Chapter heading
        body += `<w:p><w:pPr><w:pStyle w:val="Heading1"/></w:pPr>
          <w:r><w:rPr><w:b/><w:sz w:val="36"/></w:rPr><w:t>${escXml(line)}</w:t></w:r></w:p>`;
      } else {
        body += `<w:p><w:pPr><w:spacing w:after="200"/></w:pPr>
          <w:r><w:t xml:space="preserve">${escXml(line)}</w:t></w:r></w:p>`;
      }
    });
    // Page break between chapters
    body += `<w:p><w:r><w:br w:type="page"/></w:r></w:p>`;
  });

  zip.file('word/document.xml', `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="${w}">
  <w:body>${body}</w:body>
</w:document>`);

  const blob = await zip.generateAsync({ type: 'blob', mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' });
  downloadBlob(blob, sanitizeFilename(title) + '.docx');
  awardSkull(4);
}

// ═══════════════════════════════════════════
// Deployable ZIP — Reader HTML + novel JSON
// ═══════════════════════════════════════════
async function exportZip() {
  // Export ALL novels in the library as a full reader/store
  if (!STATE.novels.length) {
    alert('No novels to export. Generate at least one novel first.');
    return;
  }

  const zip = new JSZip();

  // Build catalog and curation data
  const catalog = buildExportCatalog();
  const curation = buildExportCuration();

  // Inject into reader template
  const storeName = catalog.length === 1 ? catalog[0].title : 'NaNoGEon Library';
  const settingsCss = typeof buildReaderSettingsCss === 'function' ? buildReaderSettingsCss() : '';
  let readerHtml = READER_TEMPLATE
    .replace(/__READER_TITLE__/g, escXml(storeName))
    .replace('__CATALOG_JSON__', JSON.stringify(catalog))
    .replace('__INITIAL_NOVEL__', 'null') // exported reader opens to browse
    .replace('/* __READER_SETTINGS_CSS__ */', settingsCss);

  // Inject curation data if available
  if (curation) {
    readerHtml = readerHtml.replace('// ─── Init ───', `const CURATION = ${JSON.stringify(curation)};\n// ─── Init ───`);
  }

  zip.file('index.html', readerHtml);

  const blob = await zip.generateAsync({ type: 'blob' });
  downloadBlob(blob, 'nanogeon-reader.zip');
  awardSkull(4);
}

function tropeLabelShort(key) {
  // Convert trope key to a readable tag: 'hidden-master' → 'Hidden Master'
  return key.split('-').map(w => w[0].toUpperCase() + w.slice(1)).join(' ');
}


// ═══════════════════════════════════════════
// UTILITIES
// ═══════════════════════════════════════════
function escXml(s) {
  if (!s) return '';
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&apos;');
}
