name: Certificate Request
description: Request a workshop completion certificate
title: "cert: {workshop}"
labels: ["cert-request"]
body:
  - type: input
    id: fullname
    attributes:
      label: Full Name
      description: Your name as it should appear on the certificate.
      placeholder: Ana Costa
    validations:
      required: true
  - type: input
    id: workshop
    attributes:
      label: Workshop
      description: "Workshop code (e.g. PB-101, PB-201, PB-301, PB-401)."
      placeholder: PB-101
    validations:
      required: true
  - type: input
    id: date
    attributes:
      label: Completion Date
      description: "Date you completed the workshop (YYYY-MM-DD)."
      placeholder: "2026-02-20"
    validations:
      required: true
  - type: input
    id: hash
    attributes:
      label: Completion Hash
      description: The hash shown at the end of the workshop.
      placeholder: a1b2c3d4e5f67890
    validations:
      required: true
